# Generated by Django 5.2.8 on 2025-11-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='buildings/icons/'),
        ),
        migrations.AddField(
            model_name='building',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='buildings/photos/'),
        ),
    ]
