# Generated by Django 5.2.8 on 2026-01-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_sitevisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('visitors', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
