# Generated by Django 5.2.8 on 2026-01-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_building_icon_building_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('first_visit', models.DateTimeField(auto_now_add=True)),
                ('last_visit', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
