# Generated by Django 5.2 on 2026-02-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0006_alter_university_options_building_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='universities/logos/'),
        ),
        migrations.AddField(
            model_name='university',
            name='max_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='max_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='min_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='min_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
