# Generated by Django 5.2 on 2026-02-19 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0007_university_logo_university_max_lat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusAdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.university')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='campus_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
