# Generated by Django 5.2 on 2026-02-19 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0008_campusadminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystats',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campus.building'),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campus.building'),
        ),
    ]
