# Generated by Django 5.2 on 2026-06-08 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0009_dailystats_building_sitevisit_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystats',
            name='university',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='daily_stats',
                to='campus.university',
            ),
            preserve_default=False,
        ),

        migrations.AlterField(
            model_name='dailystats',
            name='date',
            field=models.DateField(),
        ),

        migrations.RemoveField(
            model_name='dailystats',
            name='building',
        ),

        migrations.AlterUniqueTogether(
            name='dailystats',
            unique_together={('university', 'date')},
        ),

    ]
