# Generated by Django 5.2 on 2026-06-08 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0010_alter_dailystats_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitevisit',
            name='building',
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_visits', to='campus.university'),
        ),
    ]
